In [1]:
import sys as s
s.getsizeof(1) #integer

28

In [2]:
s.getsizeof('Python') #string

55

In [3]:
s.getsizeof('')

51

In [4]:
s.getsizeof('P')

50

In [5]:
s.getsizeof('Py')

51

In [6]:
s.getsizeof('Pyt')

52

In [7]:
s.getsizeof([])

56

In [8]:
s.getsizeof([1])

64

In [9]:
s.getsizeof([1,2])

72

In [10]:
s.getsizeof([1,2,3])

80

In [11]:
s.getsizeof([1,2,3,4])

88

In [12]:
lis = [1,'Ankit']
s.getsizeof(lis)

72

In [13]:
s.getsizeof([1,2,[3,4,5,1]])

80

## NUMPY 2

In [15]:
list1 = [1,2,3,4,5,6]
list2 = [10,9,8,7,6,5]

print(list1*list2)

TypeError: can't multiply sequence by non-int of type 'list'

In [17]:
import numpy as np
a1=np.array(list1)
a2=np.array(list2)

a1*a2

array([10, 18, 24, 28, 30, 30])

In [18]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8])

# a[2:] = b[::-1] 

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
b

array([6, 7, 8])

In [21]:
a[2:]

array([3, 4, 5])

In [22]:
b[::-1]

array([8, 7, 6])

In [23]:
a[2:] = b[::-1]
a

array([1, 2, 8, 7, 6])

What is size is diff

In [24]:
a[3:] = b[::-1]

ValueError: could not broadcast input array from shape (3,) into shape (2,)

In [25]:
a[1:] = b[::-1]

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [26]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
mask = a<6
mask

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False, False])

In [28]:
a[mask]

array([0, 1, 2, 3, 4, 5])

In [29]:
mask = a%2 ==0
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [30]:
a[mask]

array([ 0,  2,  4,  6,  8, 10])

In [31]:
mask1 = (a%2 ==0)
mask2 = (a%5 ==0)

a[mask1]

array([ 0,  2,  4,  6,  8, 10])

In [32]:
a[mask2]

array([ 0,  5, 10])

In [33]:
a[mask1 or mask2]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
a[mask1 | mask2]

In [34]:
a[mask1 & mask2]

array([ 0, 10])

In [35]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a>b

array([False, False, False])

In [36]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [37]:
a+3


array([3, 4, 5, 6])

In [38]:
np.sum(a) #numpy sum

6

In [39]:
a.sum() #ndarray sum

6

In [40]:
np.mean(a)

1.5

In [41]:
6/4

1.5

In [42]:
a.mean()

1.5

In [43]:
np.min(a)

0

In [44]:
np.max(a)

3

In [45]:
# Use case: Airbnb data 
# We wanted to understand customer sentiment
# Metric : NPS Score

In [57]:
#https://drive.google.com/file/d/14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8/view?usp=sharing

In [56]:
#!pip install gdown

In [51]:
!gdown 14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8

Downloading...
From: https://drive.google.com/uc?id=14bd7pg9d3CbhcxdT6EGMDgvgMHrSjKR8
To: D:\Scalar course\2.Numpy\2.Numpy-2\survey.txt

  0%|          | 0.00/2.55k [00:00<?, ?B/s]
100%|##########| 2.55k/2.55k [00:00<?, ?B/s]


In [52]:
score = np.loadtxt("/Scalar course/2.Numpy/2.Numpy-2/survey.txt",dtype="int")
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [53]:
score.shape

(1167,)

In [58]:
score.min()

1

In [59]:
score.max()

10

In [60]:
detractor_mask = (score<7)
detractor_mask

array([False, False,  True, ...,  True, False, False])

In [61]:
detractor = score[detractor_mask]

In [62]:
detractor.shape

(332,)

In [63]:
detractor_number = detractor.shape[0]
detractor_number 

332

In [64]:
total = score.shape[0]
total

1167

In [65]:
promoter_mask = (score>8)
promoter_mask

array([False,  True, False, ..., False,  True,  True])

In [66]:
promoter = score[promoter_mask]
promoter

array([10,  9,  9,  9,  9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,
       10, 10,  9, 10,  9, 10,  9,  9, 10, 10,  9, 10,  9, 10, 10, 10,  9,
        9, 10, 10, 10,  9, 10,  9, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9,
        9, 10,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9,  9, 10, 10,  9, 10,
        9,  9, 10,  9,  9, 10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10, 10,
        9, 10, 10, 10, 10,  9, 10,  9,  9,  9,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9, 10, 10, 10,  9,  9, 10, 10,  9,  9,  9,  9, 10,  9,  9,
        9,  9, 10, 10,  9,  9,  9, 10,  9,  9,  9,  9,  9, 10,  9,  9,  9,
       10,  9, 10, 10,  9,  9,  9,  9, 10,  9, 10,  9,  9,  9,  9, 10,  9,
       10,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10,  9,  9,  9,
       10,  9, 10, 10, 10, 10, 10,  9,  9,  9,  9, 10, 10, 10,  9,  9, 10,
        9, 10, 10, 10, 10,  9, 10, 10,  9, 10,  9,  9,  9,  9, 10,  9, 10,
        9, 10,  9,  9,  9

In [67]:
promoter.shape

(609,)

In [68]:
promoter_number = promoter.shape[0]
promoter_number 

609

In [69]:
percentage_promoter = (promoter_number/total)*100
percentage_promoter

52.185089974293064

In [70]:
percentage_detractor = (detractor_number/total)*100
percentage_detractor

28.449014567266495

In [71]:
nps = percentage_promoter - percentage_detractor
nps

23.73607540702657

In [76]:
import numpy as np

In [80]:
mat = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

In [82]:
mat.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [103]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers', 
         'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [104]:
a = dict(zip(birds,age))
a

{'spoonbills': 6.0, 'plovers': 2.0, 'Cranes': 5.5}

{'spoonbills': 6.0, 'plovers': 2.0, 'Cranes': 5.5}

In [87]:
my_dict = dict(zip(birds, map(int, age)))

In [88]:
my_dict

{'spoonbills': 6, 'plovers': 2, 'Cranes': 5}

In [105]:
res = list(map(lambda i,j : (i,j) , birds,age))
res

[('spoonbills', 5.5),
 ('plovers', 6.0),
 ('plovers', 3.5),
 ('plovers', 1.5),
 ('plovers', 3.0),
 ('Cranes', 4.0),
 ('plovers', 3.5),
 ('plovers', 2.0),
 ('Cranes', 5.5),
 ('spoonbills', 6.0)]

[('spoonbills', 5.5),
 ('plovers', 6.0),
 ('plovers', 3.5),
 ('plovers', 1.5),
 ('plovers', 3.0),
 ('Cranes', 4.0),
 ('plovers', 3.5),
 ('plovers', 2.0),
 ('Cranes', 5.5),
 ('spoonbills', 6.0)]

In [97]:
def Sort_Tuple(tup):
    return(sorted(tup, key = lambda x: x[1])) 

In [106]:
a1 = Sort_Tuple(res)
a1

[('plovers', 1.5),
 ('plovers', 2.0),
 ('plovers', 3.0),
 ('plovers', 3.5),
 ('plovers', 3.5),
 ('Cranes', 4.0),
 ('spoonbills', 5.5),
 ('Cranes', 5.5),
 ('plovers', 6.0),
 ('spoonbills', 6.0)]

In [101]:
a2 = []
for i in a1:
    a2.append(i[0])

In [102]:
a2

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [109]:
def sort_birds(birds, age):
    result = list(map(lambda i,j : (i,j),birds,age))
    a1 = sorted(result,key = lambda x:x[1])
    result1 = []
    for i in a1:
        result1.append(i[0])
    return result1

In [113]:
a2 = sort_birds(birds, age)
a2

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [112]:
for i in a2:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [118]:
def sort_birds(birds, age):
    result = list(map(lambda i,j : (i,j),birds,age))
    a1 = sorted(result,key = lambda x:x[1])
    result1 = []
    for i in a1:
        result1.append(i[0])
    return result1

In [119]:
sort_birds(birds, age)

['plovers',
 'plovers',
 'plovers',
 'plovers',
 'plovers',
 'Cranes',
 'spoonbills',
 'Cranes',
 'plovers',
 'spoonbills']

In [121]:
p = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [122]:
p

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [124]:
p1 = p[::2]

In [125]:
p1.flatten()

array([1, 2, 3, 7, 8, 9])

In [128]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
x.max(axis=1)

array([ 3,  7, 11])

In [130]:
x.sum()

66

In [131]:
x.T.max(axis=0)

array([ 3,  7, 11])

In [132]:
[i.min() for i in x]

[0, 4, 8]

In [153]:
import numpy as np
arr = 2*np.arange(0,2,0.5)
print(arr)
if arr.any() <= 0.6:
    
    print ("condition satisfies")
else:
    print ("condition doesn't satisfy") 

[0. 1. 2. 3.]
condition doesn't satisfy


In [157]:
print(arr.any(axis=0) <= 0.6)

False


In [166]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [167]:
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [179]:
a = np.array([[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [184]:
b = a[1:4, -3:]
b

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [187]:
b[::-1]

array([[13, 14, 15],
       [ 9, 10, 11],
       [ 5,  6,  7]])

In [189]:
np.array((3,3))

array([3, 3])

In [193]:
a = np.zeros((3, 3), int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [196]:
b = np.fill_diagonal(a, 5)
a

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])