In [1]:
import numpy as np

In [6]:
m1 = np.array([[1,2,3],[4,6,1]])

In [7]:
m1.shape

(2, 3)

In [8]:
m1.ndim

2

## creating HD Arrays

In [11]:
m2 = np.arange(1,13)

In [15]:
m2.reshape(3,-1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
m2.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
m2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [33]:
m2.reshape((3,-1))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
m2[1][2]

IndexError: invalid index to scalar variable.

In [35]:
a = np.arange(1,10).reshape((3,3))

In [36]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
a[1][1]

5

In [39]:
a[2][2]

9