In [1]:
import numpy as np

In [2]:
a = np.arange(4)

In [3]:
a

array([0, 1, 2, 3])

In [5]:
b = a.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

### creating a shallow copy

In [6]:
a[0] = 100

In [7]:
a

array([100,   1,   2,   3])

In [8]:
b

array([[100,   1],
       [  2,   3]])

In [9]:
# here we can see that the data of b also got changed.

In [10]:
np.shares_memory(a,b)

True

In [12]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [13]:
c = a+2
c

array([2, 3, 4, 5])

In [18]:
a[0]=100
a

array([100,   1,   2,   3])

In [19]:
c

array([2, 3, 4, 5])

In [20]:
np.shares_memory(a,c)

False

In [21]:
a = np.arange(10)

In [22]:
view_a = a.view()
view_a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.shares_memory(a,view_a)

True

### creating the deep copy

In [25]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
#changing the 0th index of a
a[0] = 100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [28]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.shares_memory(a,b)

False

In [30]:
# in above we can see that a and b dont share the same memory

In [31]:
c = np.array([1,'m',[1,2,3]],dtype=object)

In [32]:
d = c.copy()

In [33]:
c[2][0]=100

In [34]:
d

array([1, 'm', list([100, 2, 3])], dtype=object)

In [35]:
# here the data of d also got changednp
np.shares_memory(d,c)

False

In [36]:
# above is saying false but actually its sharing the memory in case of object dtype

## Solution

In [37]:
import copy

In [39]:
c = np.array([1,2,'m',[1,12]],dtype=object)

In [40]:
d = copy.deepcopy(c)

# part 2:

### dimension expansion and reduction:

In [43]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
b = a.reshape((3,3))
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
b.shape

(3, 3)

In [48]:
c = a.reshape((3,3,1))
c

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [49]:
c.shape

(3, 3, 1)

In [50]:
d = a.reshape(3,3,1,1,1,1,1,1,1)

In [57]:
d.ndim  # calculating the number of dim we have

9

In [67]:
a = np.arange(1,13).reshape(3,4,1)
a

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [68]:
np.expand_dims(a,axis=3).shape

(3, 4, 1, 1)

In [69]:
a = np.arange(5)
a.shape

(5,)

In [70]:
a[:,np.newaxis].shape

(5, 1)

In [72]:
a[np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,np.newaxis,:].shape

(1, 1, 1, 1, 1, 1, 5)

In [74]:
np.squeeze(a).shape

(5,)

# Splitting the array

In [77]:
a = np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [80]:
np.split(a,[4,5])

[array([1, 2, 3, 4]), array([5]), array([ 6,  7,  8,  9, 10, 11, 12])]

In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[1, 2], ["Ram", "Shyam"], ["IT", "Ops"]], columns = ["emp_id", "name", "dept"])

ValueError: 3 columns passed, passed data had 2 columns

In [11]:
df = pd.DataFrame([[1, "Ram", "IT"], [2, "Shyam", "Ops"]], columns = ["emp_id", "name", "dept"])

In [12]:
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops

In [6]:
df = pd.DataFrame([1, "Ram", "IT"], columns = ["emp_id", "name", "dept"])

ValueError: Shape of passed values is (3, 1), indices imply (3, 3)

In [7]:
df = pd.DataFrame({'emp_id':[1, 2], 'name': ['Ram', 'Shyam'], 'dept':['IT', 'Ops']})

In [8]:
df

emp_id   name dept
0       1    Ram   IT
1       2  Shyam  Ops

In [13]:
for x in df.columns:
    if df[x].nunique()==1:
        df.drop(x, axis=1, inplace=True)

In [14]:
df = pd.read_csv('tips.csv')

In [16]:
pd.DataFrame(df, columns=['time', 'total_bill', 'tip'])

time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [17]:
df[['time', 'total_bill', 'tip']]

time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [18]:
df.loc[:, ['time', 'total_bill', 'tip']]

time  total_bill   tip
0    Dinner       16.99  1.01
1    Dinner       10.34  1.66
2    Dinner       21.01  3.50
3    Dinner       23.68  3.31
4    Dinner       24.59  3.61
..      ...         ...   ...
239  Dinner       29.03  5.92
240  Dinner       27.18  2.00
241  Dinner       22.67  2.00
242  Dinner       17.82  1.75
243  Dinner       18.78  3.00

[244 rows x 3 columns]

In [19]:
df.iloc[:,0:2]

total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [34]:
n = int(input())
a = []
for i in range(n):
    i = int(input())
    
    a.append(i)
a.sort()
print(a)
print(a[-2])

6
1
3
5
4
-1
0
[-1, 0, 1, 3, 4, 5]
4
