## Agenda

- **Introduction to use Fitbit case**

- **Important Functions**  
    - `np.empty()`
    - `np.unique()`

    
- **2-D arrays (Matrices)** 
    - `reshape()`
    - Transpose
    - Converting Matrix back to Vector - `flatten()`

- **Indexing and Slicing on 2D** 
    - Indexing

    - Slicing

    - Masking (Fancy Indexing)
   

- **Universal Functions (ufunc) on 2D** 
    - Aggregate Function/ Reduction functions - `sum()`, `mean()`, `min()`, `max()`
    
    - Axis argument

    - Logical Operations
 
    - Sorting function - `sort()`, `argsort()`


- **Use Case: Fitness Data analysis**  
    - Loading data set and EDA using numpy




In [4]:
import numpy as np

In [5]:
np.empty()

TypeError: empty() missing required argument 'shape' (pos 0)

In [10]:
a = np.empty((3,3))
a

array([[2.60605835e-31, 5.21211670e-31, 1.30302917e-31],
       [5.21211670e-31, 1.13363538e-30, 3.51817877e-31],
       [1.30302917e-31, 3.51817877e-31, 2.01969522e-31]])

In [11]:
a.ndim

2

In [12]:
a = np.array([1,2,3,4,5,1,2,3,4,4,5,5,6,1,2,3])
a

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 4, 5, 5, 6, 1, 2, 3])

In [13]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [14]:
np.unique(a,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([3, 3, 3, 3, 3, 1]))

In [ ]:
#2D array

In [15]:
a = np.array([[1,2,3]])
a

array([[1, 2, 3]])

In [16]:
a.ndim

2

In [17]:
a.shape

(1, 3)

In [18]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a.ndim

2

In [20]:
a.shape

(2, 3)

In [21]:
b = np.array([[1],[2],[3],[4],[5]])
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [22]:
len(b)

5

In [ ]:
#Mask

In [23]:
a = np.array([0,4,5])
b = np.array([1,3,5])
a>=b

array([False,  True,  True])

In [29]:
a = np.array([0,1,2,3,4,5])
mask = (a%2 == 0)
a[mask] = -1

In [27]:
a

array([-1,  1, -1,  3, -1,  5])

In [ ]:
#Reshape

In [31]:
a=np.arange(1,13)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
a = a.reshape((3,4)) #(4,3), (12,1), (1,12), (2,6),(6,2)

In [38]:
a.reshape((3,5))

ValueError: cannot reshape array of size 12 into shape (3,5)

In [35]:
a.reshape((2,2,3)).ndim


3

In [ ]:
#Transpose

In [39]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [43]:
b = a.T
b

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [44]:
b.shape

(4, 3)

In [45]:
e=np.array([[1,2,3]])
e

array([[1, 2, 3]])

In [46]:
e.shape

(1, 3)

In [47]:
e.T

array([[1],
       [2],
       [3]])

In [48]:
t=np.arange(1,13).reshape((3,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
t.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
#indexing & slicing

In [50]:
t=np.arange(1,13).reshape((3,4))
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
t[0]

array([1, 2, 3, 4])

In [52]:
t[0][1] #not recommended

2

In [53]:
t[0,1] #recommended

2

In [54]:
t[1:2,0:1]

array([[5]])

In [ ]:
t[-1,-2]

In [55]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [57]:
t[[1,0,2]]

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [82]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
t[[1,0,2],[1,3,3]]  #t[[row],[column]] = (1,1),(0,3),(2,3)

array([ 6,  4, 12])

In [ ]:
#slicing

In [59]:
t[::,::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
t[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [61]:
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
t[::-1,::-1] 

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [ ]:
#Masking

In [63]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
a<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [65]:
a[a<6]

array([1, 2, 3, 4, 5])

In [66]:
a[(a<5)&(a>8)]

array([], dtype=int64)

In [ ]:
#Universal Funcstions on 2D

In [67]:
a=np.arange(1,13).reshape((3,4))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
np.sum(a)

78

In [69]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [70]:
np.mean(a,axis=0)

array([5., 6., 7., 8.])

In [ ]:
#sort(), argsort()

In [71]:
a=np.array([5,1,7,3,8,2,9,4])
a

array([5, 1, 7, 3, 8, 2, 9, 4])

In [72]:
np.sort(a)

array([1, 2, 3, 4, 5, 7, 8, 9])

In [74]:
b=np.array([[5,8,2,7],[9,5,8,0],[2,6,20,30],[7,2,8,1]])
b

array([[ 5,  8,  2,  7],
       [ 9,  5,  8,  0],
       [ 2,  6, 20, 30],
       [ 7,  2,  8,  1]])

In [78]:
np.sort(b,axis=1)

array([[ 2,  5,  7,  8],
       [ 0,  5,  8,  9],
       [ 2,  6, 20, 30],
       [ 1,  2,  7,  8]])

In [77]:
np.sort(b,axis=0)

array([[ 2,  2,  2,  0],
       [ 5,  5,  8,  1],
       [ 7,  6,  8,  7],
       [ 9,  8, 20, 30]])

In [79]:
np.argsort(b)

array([[2, 0, 3, 1],
       [3, 1, 2, 0],
       [0, 1, 2, 3],
       [3, 1, 0, 2]])

In [81]:
b

array([[ 5,  8,  2,  7],
       [ 9,  5,  8,  0],
       [ 2,  6, 20, 30],
       [ 7,  2,  8,  1]])

In [80]:
np.argmin(b,axis=0)

array([2, 3, 0, 1])